In [1]:
import pandas as pd
pd.options.display.max_rows = 230

In [2]:
df = pd.read_csv('../data_prep/payroll11_21.csv')
df.head()

,name,department_name,title,regular,retro,other,overtime,injured,detail,quinn,total_earnings,zip,year
0,"Abasciano,Joseph",Boston Police Department,Police Officer,$68181.24,$0.00,$3763.50,$14177.65,$0.00,$4867.00,$0.00,$90989.39,02132-3802,2011
1,"Abdul-Aziz,Ramadani",Boston Police Department,Police Officer,$73935.02,$0.00,$800.00,$5573.40,$0.00,$44865.00,$0.00,$125173.42,02119-1618,2011
2,"Abichaker,Linda",Boston Police Department,Police Clerk And Typist,$34958.02,$0.00,$0.00,$0.00,$0.00,$0.00,$0.00,$34958.02,02132-2737,2011
3,"Abreu,Cesar",Boston Police Department,Police Officer,$69701.19,$0.00,$800.00,$37800.40,$0.00,$29826.00,$0.00,$138127.59,02136-1540,2011
4,"Abron,Kim R.",Boston Police Department,School Traffic Supv,$10129.29,$0.00,$450.00,$0.00,$0.00,$0.00,$0.00,$10579.29,02124-4819,2011

In [3]:
df.fillna(0, inplace=True)
df.head()

,name,department_name,title,regular,retro,other,overtime,injured,detail,quinn,total_earnings,zip,year
0,"Abasciano,Joseph",Boston Police Department,Police Officer,$68181.24,$0.00,$3763.50,$14177.65,$0.00,$4867.00,$0.00,$90989.39,02132-3802,2011
1,"Abdul-Aziz,Ramadani",Boston Police Department,Police Officer,$73935.02,$0.00,$800.00,$5573.40,$0.00,$44865.00,$0.00,$125173.42,02119-1618,2011
2,"Abichaker,Linda",Boston Police Department,Police Clerk And Typist,$34958.02,$0.00,$0.00,$0.00,$0.00,$0.00,$0.00,$34958.02,02132-2737,2011
3,"Abreu,Cesar",Boston Police Department,Police Officer,$69701.19,$0.00,$800.00,$37800.40,$0.00,$29826.00,$0.00,$138127.59,02136-1540,2011
4,"Abron,Kim R.",Boston Police Department,School Traffic Supv,$10129.29,$0.00,$450.00,$0.00,$0.00,$0.00,$0.00,$10579.29,02124-4819,2011

In [4]:
df.title.value_counts()

Police Officer                    14408
Police Detective                   3263
School Traffic Supv                2096
Police Sergeant                    1522
Police Sergeant (Det)              1291
CommunEquipOp III, R-13 (CT)        637
Police Clerk And Typist             570
Police Offc Comm Serv Offc 3$8      557
Police Lieutenant                   536
Police Offc Mobile Offc 2$6         471
Police Dispatcher                   438
Communic. EquipOp II 9II(SS)        383
Head Clerk & Secretary              319
Jr  Building Custodian              305
Police Offc Acad Instr 2$6          293
Police Lieutenant (Det)             288
Police Offc/FgrPrt Ev Tch 4$10      277
Cadet (Police)                      232
Mtr Eq Rpprs ClassIBPDFleetBFD      222
Police Captain/DDC                  184
Prin Admin Asst                     183
Police Offc Canine 2$6              177
Police Offc/Juvenile Offc 4$10      168
Police Officer Hdq Dispatch         165
ChCommEquipOper I (SCTT)            151
Dep Supn (Bpd)                      140
Police Offc/Auto Invest 4$10        137
Exec Sec (B.P.D.)                   127
Jr Building Custodian               124
Police Offc Harborboat 3$8          120
Community Services Offc             119
Police Sergeant/Comm Serv Offc      114
Sr Radio Communications Tech        114
Supn Bpd                            109
Police Sergeant/CHF RADIO DISP      106
Police Offc Hackney Invest 3$8      104
Sr Accountant                       102
Liaison Agent (BPD)                  99
Police Offc/Bomb Squad               98
Criminalist II                       95
Police Offc Canine Offc 2$6          95
PoliceSergeant/SupvCourtCases        88
Management Analyst (Bpd)(Asse)       80
Police Sergeant/FgrPrt Ev Tech       79
Prin Research Analyst                76
Criminalist IV                       72
Police Offc Bomb Squad               72
Social Worker (BPD)                  66
Police Sergeant/Mobile Oper          66
MtrEquipRpprClassIIBPDFleetBFD       66
Criminalist III                      64
Exec Asst (BPD)                      64
Police Offc Ballistician 4$10        62
Sr Bldg Custodian (BPD)##            59
Criminalist I                        57
Research Analyst                     56
Sr Admin Anl                         52
Police Officer Harborboat 3$8        50
Statistical Analyst(Bpd)             48
Office Manager                       44
Police Offc/Hosp Liaison 4$10        44
Data Proc Sys Analyst                44
Chaplain                             43
Sr Data Proc Sys Anl                 43
Data Proc Equip Tech (BPD)           43
Admin Asst                           42
Sr Programmer                        42
Police Sergeant/AcadInstructor       41
Police Captain (Det)                 36
Sr Budget Anl (BPD)(H&H)             36
Prin Storekeeper                     36
Police Captain                       34
Sr Admin Asst                        34
Signalperson-Electrician             33
Offset Compositor                    31
Police Lieutenant/Hdq Dispatch       31
Asst Prin Accountant                 31
Support Desk Specialist              31
Head Clerk                           27
Police Sergeant/Pd Det Serv          27
Head Admin Clerk                     26
Police Sergeant/Bomb Squad           24
Police Sergeant/Hackney Invest       23
Interpreter                          22
ACC - Attorney                       22
Collection Agent I                   22
Police Officer Mobile Oper 2$6       21
Liaison Agent II                     21
Buyer                                21
Admin Secretary                      21
Project Coor                         21
Sergeant/Harbor Patrol               21
Exec Sec (B.P.D)                     20
IBIS Support Technician              20
Sr Personnel Officer II              20
Police Lieut/Acad Instr              19
Sr Data Proc Sys Anl (ASD/DPU)       19
Prin Accountant                      19
Criminalist                          17
Police Offc Breath $13.50            16
Police Lieutenant/Mobile Oper        16
Legal Asst (BPD)                     16
Prin Personnnel Officer              15
Collection Agent(Bpd)                14
Policy Analyst ARRA                  14
Student Intern                       14
Police Captain-DDC/HRCD              14
Sr Criminalist                       14
Commissioner (Bpd)                   14
Audio Visual Tech & Photogr##        14
Police Sergeant/Hdq Dispatcher       13
Supv Mtr Equip Rpprs (BPD)           13
Supn-In Chief                        13
Management Analyst                   13
Research Assist (Bpd)                13
Exec Sec    (Int)                    13
Sr Personnel Analyst                 12
Dir-Forensic Quality Control         12
Supv Graphic Arts Svc (BPD)          12
Store Control Supv(Bpd Fleet)        12
Radio Supv (Bpd)                     12
Police Lieut (Det)                   12
Exec Sec (Bpd)                       12
Personnel Officer                    12
IAPRO Systems Coordinator            11
Head Trainer                         11
Supn Auto Maint(Bpdfleet)            11
Staff Asst (Administration)          11
Supn-Custodians (Buildings)          11
Employee Development Asst(Ems)       11
Public Relations Rep(Bpd)            11
Building Maint Supv                  11
Supv-Payrolls                        11
Building Systems Engineer            11
Dir-Crimalistic Services(Bpd)        11
Tape Librarian I (BPD)               11
Legal Secretary                      11
Maint Mech (Painter-Bpd)             11
Video Forensic Analyst               11
Data Proc Svcs Director(Bpd)         11
Dir-Transportation (Bpd)/(Bfd)       11
Asst Payroll Supv                    11
Data Proc Coordinator                11
Prin Dp Sys Anal-Dp                  11
Dir-Public Info (Police)             11
Tape Librarian(Oper/Bpd)             11
Dir-Signal Service (Bpd)             11
Distance Learning Coord ARRA         11
Personnel Asst                       10
Employee Development Coor            10
Dir of Human Resources (BPD)         10
Asst Corp Counsel I                  10
Admin Asst (Police)                  10
Sr Employee Development Asst         10
Dir of Health & Wellness             10
Supv Contract-Orders (Rpd BPD)        9
Admin Anl                             9
Admin Asst/EvidencTechncn(BPD)        9
Maint Mech - HVAC Technician          9
Claims Investigator                   9
Police Lieut/Paid Detail Ser          9
Supn-Police Buildings                 9
Prin Personnel Officer                9
Admin  Secretary (BPD)                8
Prin Admin Asst (Bpd/Adm.)            8
Worker's Compensation Case Mgr        8
Admin Asst (Finance)                  8
Dir/OfficeofResearch&DeveloBPD        7
Lab Informatioin Mgmt Admn BPD        7
Police Capt/DDC-Hackney Inves         7
Dir of Quality Assurance (BPD)        7
Dir of Latent Print Unit (BPD)        7
Lieut-Hackney Carriage Inves.         7
ACC - Management                      6
Staff Asst Pol Comr (BurAdmSvc        6
Dep Chief Staff                       6
Crimilalist IV                        6
Capt.D.D.C-pd Details Section         6
Staff Asst/Chf Bureau Adm Serv        6
BPD Homicide Intelligence Anl         5
Head Accountant                       5
Police Offc RadioTech                 5
Mobile Tech Spec (BPD)                5
ACC - Sr Attorney                     5
Motor Equip Repprs ClassIIIBPD        5
DiversityRecruitmntOff&ExmAdmn        5
DataProgrmming&ApplicationTech        5
AssocDir,BPDOfficeofReas&Devel        4
Dep Dir Chief Financial Offcr         4
Dep Dir of Human Resources BPD        4
Community Rel Specialist (Bpd)        4
Asst Dir BPD Neigh Crime Watch        4
Police Captain/Hackney Invest         4
Captain/Supv of Court Cases           4
Lab Tech##                            4
Prin Admin Asst Asd Pers              4
Captain/Academy Instructor            3
Fusion Center Coordinator             3
Director of Projects & Initiat        3
Contract Manager                      3
Fleet Operations Mgr                  3
Digital Video Technician              3
Executive Coordinator                 3
Technology Support Specialist         3
Sr Homeland Security Anl ARRA         3
Child Abuse Advocate                  3
Transportation Analyst                3
Executive Secretary (B.P.D)           3
ProgramAsst-TemporaryGrantFund        3
Exec Asst                             3
Sr Project Coordinator                2
Supn of Police Building               2
Director of Finance (BPD)             2
Police Offc Aide Comm 3$8             2
DDACTS Analyst                        2
Medical Tech##                        2
Sr Research Analyst                   2
Communications EquipOper I-911        2
Research Analyst (BPD)                2
Employment Agreement                  2
Mobile Device Technician              1
Sr Technical Project Mgr              1
STC(SecuringtheCity)ProgDirBPD        1
Dir, BosRegIntelCntr (Red-Cir)        1
Homicide Victim Witness Advoc         1
Homeland Security Supv ARRA           1
Police Sergeant/Spc Hdq Dispch        1
Crime Analyst ARRA                    1
Supv Med Tech##                       1
Data Anlys & Sys App Tech             1
Name: title, dtype: int64

In [5]:
df_bpd = pd.read_csv('../input/bpd.csv')
df_bpd.head()

,ia_number,incident_type,received_date,year,title_rank,first_name,last_name,keyname,race,gender,name_known,badge_number,allegation,finding,outcome
0,I2010-001,II,1/5/10,2010.0,Police Officer,Carlos A,Martinez,MartinezCarlosA,H,M,y,2244,Reporting for Duty,Sustained,Oral Reprimand
1,I2010-003,II,1/5/10,2010.0,Detective,Molwyn A,Shaw,ShawMolwynA,B,M,y,983,Reporting for Duty,Sustained,Oral Reprimand
2,E2010-002,CC,1/6/10,2010.0,Sergeant Detective,John J,Fitzgerald,FitzgeraldJohnJ,W,M,y,115,Neg.Duty/Unreasonable Judge,Exonerated,NaN
3,E2010-002,CC,1/6/10,2010.0,Sergeant,Edwin,Guzman,GuzmanEdwin,H,M,y,6595,Neg.Duty/Unreasonable Judge,Exonerated,NaN
4,E2010-002,CC,1/6/10,2010.0,Police Officer,Lynwood,Jenkins,JenkinsLynwood,B,M,y,1218,Neg.Duty/Unreasonable Judge,Exonerated,NaN

In [6]:
df_bpd.title_rank.value_counts()

Police Officer               5474
Detective                     658
Sergeant                      588
Sergeant Detective            270
Lieutenant                    137
Captain                       104
Lieutenantenant Detective      78
Deputy Superintendent          30
Superintendent                 14
Lieutenantenant                 5
Deputy                          3
Comiss                          1
Name: title_rank, dtype: int64

In [7]:
df[df.title.str.contains('Officer') | df.title.str.contains('Offc')]

,name,department_name,title,regular,retro,other,overtime,injured,detail,quinn,total_earnings,zip,year
0,"Abasciano,Joseph",Boston Police Department,Police Officer,$68181.24,$0.00,$3763.50,$14177.65,$0.00,$4867.00,$0.00,$90989.39,02132-3802,2011
1,"Abdul-Aziz,Ramadani",Boston Police Department,Police Officer,$73935.02,$0.00,$800.00,$5573.40,$0.00,$44865.00,$0.00,$125173.42,02119-1618,2011
3,"Abreu,Cesar",Boston Police Department,Police Officer,$69701.19,$0.00,$800.00,$37800.40,$0.00,$29826.00,$0.00,$138127.59,02136-1540,2011
5,"Ace,Richard K.",Boston Police Department,Police Officer,$68181.24,$0.00,$800.00,$11180.66,$0.00,$20695.00,$7644.20,$108501.10,02136-4045,2011
7,"Acevedo,Rafael W.",Boston Police Department,Police Officer,$69070.41,$0.00,$800.00,$14745.51,$0.00,$21997.00,$0.00,$106612.92,02125-2618,2011
...,...,...,...,...,...,...,...,...,...,...,...,...,...
34280,"Conway,Kendra J",Boston Police Department,Police Officer,0,0,800.00,0,0,0,0,800.00,2465,2021
34281,"Curtis,Christopher",Boston Police Department,Police Officer,0,0,800.00,0,0,0,0,800.00,2131,2021
34282,"Mejia,Alfred",Boston Police Department,Police Officer,790.07,0,0,0,0,0,0,790.07,2136,2021
34283,"Pires,Luis",Boston Police Department,Police Officer,790.07,0,0,0,0,0,0,790.07,2125,2021
34284,"Rogers,Michelle M.",Boston Police Department,Police Officer,790.07,0,0,0,0,0,0,790.07,2125,2021

In [8]:
officers = df[df.title.str.contains('Officer') | df.title.str.contains('Offc')]

In [9]:
detectives = df[df.title.str.contains('Detective') | df.title.str.contains('(Det)')]

/var/folders/8w/c7bhb4y56693wcs88hywlmq00000gn/T/ipykernel_38832/116757094.py:1: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  detectives = df[df.title.str.contains('Detective') | df.title.str.contains('(Det)')]

In [10]:
sergeants = df[df.title.str.contains('Sergeant')]

In [11]:
lieutenants = df[df.title.str.contains('Lieutenant')]

In [12]:
captains = df[df.title.str.contains('Capt')]

In [13]:
dep_supns = df[df.title.str.contains('Dep Supn')]

In [14]:
supns = df[df.title.str.contains('^Supn')]

In [15]:
commissioners = df[df.title.str.contains('Commissioner')]

In [16]:
df_guys = pd.concat([officers, detectives, sergeants, lieutenants, captains, dep_supns, supns, commissioners])

In [17]:
df_guys

,name,department_name,title,regular,retro,other,overtime,injured,detail,quinn,total_earnings,zip,year
0,"Abasciano,Joseph",Boston Police Department,Police Officer,$68181.24,$0.00,$3763.50,$14177.65,$0.00,$4867.00,$0.00,$90989.39,02132-3802,2011
1,"Abdul-Aziz,Ramadani",Boston Police Department,Police Officer,$73935.02,$0.00,$800.00,$5573.40,$0.00,$44865.00,$0.00,$125173.42,02119-1618,2011
3,"Abreu,Cesar",Boston Police Department,Police Officer,$69701.19,$0.00,$800.00,$37800.40,$0.00,$29826.00,$0.00,$138127.59,02136-1540,2011
5,"Ace,Richard K.",Boston Police Department,Police Officer,$68181.24,$0.00,$800.00,$11180.66,$0.00,$20695.00,$7644.20,$108501.10,02136-4045,2011
7,"Acevedo,Rafael W.",Boston Police Department,Police Officer,$69070.41,$0.00,$800.00,$14745.51,$0.00,$21997.00,$0.00,$106612.92,02125-2618,2011
...,...,...,...,...,...,...,...,...,...,...,...,...,...
21739,"Gross,William G.",Boston Police Department,Commissioner (Bpd),"220,672.34","15,008.25","19,774.65",0,0,0,0,"255,455.24",2131,2018
24911,"Gross,William G.",Boston Police Department,Commissioner (Bpd),"249,999.88",-,"9,654.08",-,-,-,-,"259,653.96",2131,2019
28181,"Gross,William G.",Boston Police Department,Commissioner (Bpd),"$249,999.88",0,"$9,615.38",0,0,0,0,"$259,615.26",2131,2020
32225,"White,Dennis A",Boston Police Department,Commissioner (Bpd),"111,841.39",0,"39,261.54",0,0,0,"6,791.36","157,894.29",2368,2021
32606,"Gross,William G.",Boston Police Department,Commissioner (Bpd),"28,846.14",0,"110,089.94",0,0,0,0,"138,936.08",2186,2021

In [18]:
df_bpd

,ia_number,incident_type,received_date,year,title_rank,first_name,last_name,keyname,race,gender,name_known,badge_number,allegation,finding,outcome
0,I2010-001,II,1/5/10,2010.0,Police Officer,Carlos A,Martinez,MartinezCarlosA,H,M,y,2244,Reporting for Duty,Sustained,Oral Reprimand
1,I2010-003,II,1/5/10,2010.0,Detective,Molwyn A,Shaw,ShawMolwynA,B,M,y,983,Reporting for Duty,Sustained,Oral Reprimand
2,E2010-002,CC,1/6/10,2010.0,Sergeant Detective,John J,Fitzgerald,FitzgeraldJohnJ,W,M,y,115,Neg.Duty/Unreasonable Judge,Exonerated,NaN
3,E2010-002,CC,1/6/10,2010.0,Sergeant,Edwin,Guzman,GuzmanEdwin,H,M,y,6595,Neg.Duty/Unreasonable Judge,Exonerated,NaN
4,E2010-002,CC,1/6/10,2010.0,Police Officer,Lynwood,Jenkins,JenkinsLynwood,B,M,y,1218,Neg.Duty/Unreasonable Judge,Exonerated,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7580,NaN,NaN,NaN,NaN,NaN,Robert A,Ward,WardRobertA,W,M,y,NaN,NaN,NaN,NaN
7581,NaN,NaN,NaN,NaN,Police Officer,Donald,Wightman,WightmanDonald,W,M,y,NaN,NaN,NaN,NaN
7582,NaN,NaN,NaN,NaN,NaN,Anthony,Williams,WilliamsAnthony,B,M,y,NaN,NaN,NaN,NaN
7583,NaN,NaN,NaN,NaN,NaN,Pamela D,Wilson,WilsonPamelaD,B,F,y,NaN,NaN,NaN,NaN
7584,NaN,NaN,NaN,NaN,Police Officer,Frank,Wong,WongFrank,A,M,y,NaN,NaN,NaN,NaN

In [19]:
df_guys.name = df_guys.name.str.replace(",","")
df_guys.name = df_guys.name.str.replace(" ","")
df_guys.name = df_guys.name.str.replace(".","")

/var/folders/8w/c7bhb4y56693wcs88hywlmq00000gn/T/ipykernel_38832/2428563797.py:3: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  df_guys.name = df_guys.name.str.replace(".","")

In [20]:
df_guys.total_earnings = df_guys.total_earnings.str.replace("$","")
df_guys.total_earnings = df_guys.total_earnings.str.replace(",","")
df_guys.total_earnings = df_guys.total_earnings.astype(float)

/var/folders/8w/c7bhb4y56693wcs88hywlmq00000gn/T/ipykernel_38832/4223185009.py:1: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  df_guys.total_earnings = df_guys.total_earnings.str.replace("$","")

In [21]:
df_guys.name = df_guys.name.str.lower()

In [22]:
df_guys[df_guys.name == 'abreucesar']

,name,department_name,title,regular,retro,other,overtime,injured,detail,quinn,total_earnings,zip,year
3,abreucesar,Boston Police Department,Police Officer,$69701.19,$0.00,$800.00,$37800.40,$0.00,$29826.00,$0.00,138127.59,02136-1540,2011
3016,abreucesar,Boston Police Department,Police Officer,$69701.20,$0.00,$800.00,$27796.44,$0.00,$23932.00,$0.00,122229.64,02136-1540,2012
6051,abreucesar,Boston Police Department,Police Officer,$69836.75,$0.00,$800.00,$64216.88,$0.00,$23668.00,$0.00,158521.63,02136-1540,2013
9136,abreucesar,Boston Police Department,Police Officer,$80639.45,$12530.09,$1716.06,$50922.44,$0.00,$14127.00,$0.00,159935.04,02136,2014
12314,abreucesar,Boston Police Department,Police Officer,$86331.52,$0.00,$800.00,$46469.48,$0.00,$21253.00,$0.00,154854.00,02136,2015
15348,abreucesar,Boston Police Department,Police Officer,"$85,849.67",0,"$6,680.12","$50,193.20",0,"$40,158.00",0,182880.99,02136,2016
20433,abreucesar,Boston Police Department,Police Officer,"$89,199.53","$6,634.17","$7,055.50","$23,782.75","$2,334.80",0,0,129006.75,2136,2017
22309,abreucesar,Boston Police Department,Police Officer,"95,817.00",0,"7,224.82","65,777.38",0,0,0,168819.20,2136,2018
26554,abreucesar,Boston Police Department,Police Officer,"60,143.09",-,800.00,"25,870.10","37,853.59",414.00,-,125080.78,2136,2019
29035,abreucesar,Boston Police Department,Police Sergeant,"$119,678.12",0,$800.00,"$43,322.09","$2,402.50",0,0,166202.71,2136,2020
31746,abreucesar,Boston Police Department,Police Sergeant,"131,790.87",0,800.00,"59,330.23",0,0,0,191921.10,2136,2021

In [23]:
one = df_bpd[df_bpd.keyname == 'AbreuCesar']
two = df_bpd[df_bpd.keyname == 'WongFrank']

pd.concat([one, two])

,ia_number,incident_type,received_date,year,title_rank,first_name,last_name,keyname,race,gender,name_known,badge_number,allegation,finding,outcome
1349,IAD2011-0548,CC,12/5/11,2011.0,Police Officer,Cesar,Abreu,AbreuCesar,H,M,y,1012,Neg.Duty/Unreasonable Judge,Sustained,Suspension
3858,IAD2014-0612,II,12/31/14,2014.0,Police Officer,Cesar,Abreu,AbreuCesar,H,M,y,1012,Reporting for Duty,Sustained,Suspension
3859,IAD2014-0612,II,12/31/14,2014.0,Police Officer,Cesar,Abreu,AbreuCesar,H,M,y,1012,Sleeping On Duty,Sustained,Suspension
3860,IAD2014-0612,II,12/31/14,2014.0,Police Officer,Cesar,Abreu,AbreuCesar,H,M,y,1012,Reporting for Duty,Sustained,Suspension
3927,IAD2015-0044,CC,1/30/15,2015.0,Police Officer,Cesar,Abreu,AbreuCesar,H,M,y,1012,Conduct Unbecoming,Unfounded,NaN
3939,IAD2015-0056,CC,2/10/15,2015.0,Police Officer,Cesar,Abreu,AbreuCesar,H,M,y,1012,CORI Access,Unfounded,NaN
4151,IAD2015-0221,CC,5/13/15,2015.0,Police Officer,Cesar,Abreu,AbreuCesar,H,M,y,1012,Neg.Duty/Unreasonable Judge,Unfounded,NaN
4152,IAD2015-0221,CC,5/13/15,2015.0,Police Officer,Cesar,Abreu,AbreuCesar,H,M,y,1012,Respectful Treatment,Unfounded,NaN
4384,IAD2015-0491,II,10/16/15,2015.0,Police Officer,Cesar,Abreu,AbreuCesar,H,M,y,1012,Conduct Unbecoming,Not Sustained,NaN
4385,IAD2015-0491,II,10/16/15,2015.0,Police Officer,Cesar,Abreu,AbreuCesar,H,M,y,1012,Conduct Unbecoming,Sustained,Suspension
4386,IAD2015-0491,II,10/16/15,2015.0,Police Officer,Cesar,Abreu,AbreuCesar,H,M,y,1012,Situations Involving Family & Frien,Unfounded,NaN
4600,IAD2016-0090,CC,3/16/16,2016.0,Police Officer,Cesar,Abreu,AbreuCesar,H,M,y,1012,Respectful Treatment,Unfounded,NaN
4773,IAD2016-0253,II,7/1/16,2016.0,Police Officer,Cesar,Abreu,AbreuCesar,H,M,y,1012,Conduct Unbecoming,Sustained,Suspension
4774,IAD2016-0253,II,7/1/16,2016.0,Police Officer,Cesar,Abreu,AbreuCesar,H,M,y,1012,Conformance to Laws,Unfounded,NaN
6063,IAD2018-0471,II,10/24/18,2018.0,Police Officer,Cesar,Abreu,AbreuCesar,H,M,y,1012,Conformance to Laws,Sustained,Suspension
7584,NaN,NaN,NaN,NaN,Police Officer,Frank,Wong,WongFrank,A,M,y,NaN,NaN,NaN,NaN

In [24]:
test = df_bpd[df_bpd.keyname == 'AbreuCesar']
years = df_guys.year.unique()
allegations = [0]*len(years)
sustained = [0]*len(years)
count = 0
for year in years:
    if year in test.year.values:
        allegations[count] = test[test.year == year].allegation.count()
        sustained[count] = test[(test.year == year) & (test.finding == 'Sustained')].finding.count()
    count += 1


new_stuff = pd.DataFrame({'year': years, 'allegations': allegations, 'sustained': sustained})
test_df = pd.DataFrame(df_guys[df_guys.name == 'abreucesar'])
test_df = test_df.merge(new_stuff, on='year', how='left')




test_df.head(30)

,name,department_name,title,regular,retro,other,overtime,injured,detail,quinn,total_earnings,zip,year,allegations,sustained
0,abreucesar,Boston Police Department,Police Officer,$69701.19,$0.00,$800.00,$37800.40,$0.00,$29826.00,$0.00,138127.59,02136-1540,2011,1,1
1,abreucesar,Boston Police Department,Police Officer,$69701.20,$0.00,$800.00,$27796.44,$0.00,$23932.00,$0.00,122229.64,02136-1540,2012,0,0
2,abreucesar,Boston Police Department,Police Officer,$69836.75,$0.00,$800.00,$64216.88,$0.00,$23668.00,$0.00,158521.63,02136-1540,2013,0,0
3,abreucesar,Boston Police Department,Police Officer,$80639.45,$12530.09,$1716.06,$50922.44,$0.00,$14127.00,$0.00,159935.04,02136,2014,3,3
4,abreucesar,Boston Police Department,Police Officer,$86331.52,$0.00,$800.00,$46469.48,$0.00,$21253.00,$0.00,154854.00,02136,2015,7,1
5,abreucesar,Boston Police Department,Police Officer,"$85,849.67",0,"$6,680.12","$50,193.20",0,"$40,158.00",0,182880.99,02136,2016,3,1
6,abreucesar,Boston Police Department,Police Officer,"$89,199.53","$6,634.17","$7,055.50","$23,782.75","$2,334.80",0,0,129006.75,2136,2017,0,0
7,abreucesar,Boston Police Department,Police Officer,"95,817.00",0,"7,224.82","65,777.38",0,0,0,168819.20,2136,2018,1,1
8,abreucesar,Boston Police Department,Police Officer,"60,143.09",-,800.00,"25,870.10","37,853.59",414.00,-,125080.78,2136,2019,0,0
9,abreucesar,Boston Police Department,Police Sergeant,"$119,678.12",0,$800.00,"$43,322.09","$2,402.50",0,0,166202.71,2136,2020,0,0
10,abreucesar,Boston Police Department,Police Sergeant,"131,790.87",0,800.00,"59,330.23",0,0,0,191921.10,2136,2021,0,0

In [25]:
altered = []

for name in df_guys.name.unique():
    years = df_guys.year.unique()
    allegations = [0]*len(years)
    sustained = [0]*len(years)
    count = 0
    if name in df_bpd.keyname.unique():
        temp_bpd = df_bpd[df_bpd.keyname == name]
        temp_payroll = df_guys[df_guys.name == name]
        # things lol 
        for year in years:
            if year in temp_bpd.year.values:
                allegations[count] = temp_bpd[temp_bpd.year == year].allegation.count()
                sustained[count] = temp_bpd[(temp_bpd.year == year) & (temp_bpd.finding == 'Sustained')].finding.count()
            count += 1
    else:
        temp_payroll = df_guys[df_guys.name == name]
        # set new columns to be empty
    new_stuff = pd.DataFrame({'year': years, 'allegations': allegations, 'sustained': sustained})
    temp_prepped = temp_payroll.merge(new_stuff, on='year', how='left')
    altered.append(temp_prepped)


len(altered)

3289

In [26]:
# Back a couple steps! Think about how to organize data
altered[0]

,name,department_name,title,regular,retro,other,overtime,injured,detail,quinn,total_earnings,zip,year,allegations,sustained
0,abascianojoseph,Boston Police Department,Police Officer,$68181.24,$0.00,$3763.50,$14177.65,$0.00,$4867.00,$0.00,90989.39,02132-3802,2011,0,0
1,abascianojoseph,Boston Police Department,Police Officer,$69432.97,$0.00,$800.00,$16767.14,$0.00,$1767.00,$0.00,88767.11,02132-3802,2012,0,0
2,abascianojoseph,Boston Police Department,Police Officer,$66673.45,$0.00,$800.00,$20318.50,$3163.30,$890.00,$0.00,91845.25,02132-3802,2013,0,0
3,abascianojoseph,Boston Police Department,Police Officer,$19469.90,$10200.36,$1491.24,$2565.64,$60753.78,$2553.00,$825.04,97858.96,02132,2014,0,0
4,abascianojoseph,Boston Police Department,Police Officer,$-886.20,$0.00,$8088.35,$544.83,$81996.78,$0.00,$20667.80,110411.56,02132,2015,0,0
5,abascianojoseph,Boston Police Department,Police Officer,"$6,933.66",0,$850.00,$205.92,"$74,331.86",0,"$15,258.44",97579.88,02132,2016,0,0
6,abascianojoseph,Boston Police Department,Police Officer,"$86,806.50","$2,070.86","$1,350.00","$23,739.40","$1,705.30","$15,502.00","$17,361.76",148535.82,2132,2017,0,0
7,abascianojoseph,Boston Police Department,Police Officer,"90,557.56",0,850.00,"29,670.66","1,009.61","7,912.00","21,050.91",151050.74,2132,2018,0,0
8,abascianojoseph,Boston Police Department,Police Officer,"94,156.49",-,850.00,"26,496.59",-,"5,980.00","23,539.21",151022.29,2132,2019,0,0
9,abascianojoseph,Boston Police Department,Police Officer,"$96,890.67",0,$850.00,"$16,595.52",0,0,"$24,222.83",138559.02,2132,2020,0,0
10,abascianojoseph,Boston Police Department,Police Officer,"7,612.84",0,"1,715.10",0,"87,115.09",0,"23,682.13",120125.16,3851,2021,0,0

In [27]:
df_guys.to_csv('../data_prep/payroll_prepped.csv', index=False)